/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number
export interface MyStruct {
  program: string
  comments: unknown[]
}
export interface TheComment {
  text: string
  spanLo: number
  spanHi: number
}
export function parseSync(s: string): MyStruct
